### ISSUE TITLE
Links are buggy when they contain the + character

### ISSUE THREAD

**Issue by arcanis** [arcanis/secretsanta#1]
Because these characters are sometimes replaced by "%20"

**Comment by stevedee** [comment]
Hi Mael, many thanks for this Secret Santa. We are all now ready for Christmas!

However with any browser on Linux, all spaces (%20) had to be replaced with "+" in order to view the 2nd name. May need to be conditional based on OS type?

**Comment by joejoe31b** [comment]
This also creates problems if the link is sent over Facebook as it gets interpreted by their external link function (with plusses getting replaced by %20).

**Comment by arcanis** [comment]
Thanks! Should be fixed by #3, let me know :)

**Comment by stevedee** [comment]
Yep, that's fixed it, and it also "survives" Facebook.
