### ISSUE TITLE
Error with multiple conditions

### ISSUE THREAD

**Issue by swishi** [arcanis/secretsanta#11]
Hello Maël

I was trying to run your script with multiple conditions like excluding to member to be paried and force one member to bi paires with antoter: 

Sophie (Niederholz) !Ismael (Gotthard)
Ismael (Gotthard) !Sophie (Niederholz)
Ismael (Gotthard) =Däddi (Geisswägi)
Däddi (Geisswägi)
Cello (Hörnliallee)
Toni (Breitenbach)
Sabine (Basel)

Pressing on "Generate your pairings" The script does not do anything? Is there anythin wron in the sytay of my list or somethin in your script?

Thanks for little Answer

Ismael

**Comment by evilalmus** [comment]
Try like this:
-------------------------
Sophie (Niederholz) !Ismael
Ismael (Gotthard) !Sophie
Ismael (Gotthard) =Däddi
Däddi (Geisswägi)
Cello (Hörnliallee)
Toni (Breitenbach)
Sabine (Basel)
-------------------------
(note that the exclusions and the forced parings do not have the (notes) after the names)

**Comment by arcanis** [comment]
Hopefully the new UI will make this process easier!
