### ISSUE TITLE
bitcoin.ico?

### ISSUE THREAD

**Issue by Firesphere** [arcanis/secretsanta#13]
What's up with the bitcoin/miner stuff?

**Comment by kelvinbward** [comment]
I was thinking the same thing, looking awful sus.... @arcanis what's up with the esoteric bitcoin stuff?

**Comment by arcanis** [comment]
Are you really qualifying an unused bitcoin icon file of "awful sus" and "esoteric stuff"?...

It's legacy. A long time ago I had an address displayed to receive possible donations, now I don't. Address got removed, forgot to remove the file.

**Comment by kelvinbward** [comment]
I'm being facetious, but in all seriousness I don't understand what the Cryptojs stuff is and how its being used.

The site itself is really cool, thanks for putting it together.
