### ISSUE TITLE
Ability to add more info or additional notes

### ISSUE THREAD

**Issue by evilalmus** [arcanis/secretsanta#14]
I have already built a form to get the people that are participating to submit info about themselves to "help" their Santa. Things like: Favorite books/hobbies, allergies, clothing sizes, etc. Right now I can put all of that inside the parenthesis so that it will be delivered to the Santa but there is no way to format it. The ability to add line breaks in the notes (/n) would solve this, or to add multiple notes per participant. Would this be a difficult addition?

Example:
Almus (Address: 123 Noname Dr, Somplace CA, 98111)(Favorite books: Neromancer)(Alergies: None) !Joe

**Comment by arcanis** [comment]
This is now supported (either using parentheses, or via the cog button on the UI view).
