### ISSUE TITLE
Exclusions without including info in ()

### ISSUE THREAD

**Issue by tecknojock** [arcanis/secretsanta#16]
I use the () to include a link to a person's preferences for the Secret Santa. It gets a little bit cumbersome to add the link when you're dealing with exclusions, and cuts down on readability for the purposes of error checking.

What I'd expect is for this to exclude Dave:
Jon (Some Info Here) !Dave
Dave (Some Info Here)
Paul (Some Info here) 

Right now it has to be
Jon (Some Info Here) !Dave (Some Info Here)

**Comment by arcanis** [comment]
This should be easier with the new UI
