### ISSUE TITLE
Amazon references

### ISSUE THREAD

**Issue by Sailfish** [arcanis/secretsanta#17]
Greetings arcanis, in review of the Javascript in index.html there are multiple references to Amazon but it's unclear what it is being used for since the rendering doesn't address it. Are these simply stubs for some future feature or something else?

Please advise.

**Comment by arcanis** [comment]
At some point I was considering giving the option to add an Amazon referral banner to the gift pages. This way, players would have had a direct link towards one of the main place they could look for Secret Santa ideas, and it'd have helped remunerate the project a little bit without compromising its purpose.

But getting a referral link was a bit of work I've been to lazy to do, so it's currently disabled.

**Comment by Sailfish** [comment]
Quick and detailed response much appreciate.
