### ISSUE TITLE
Log links break in Outlook email

### ISSUE THREAD

**Issue by Sailfish** [arcanis/secretsanta#18]
When Copy/Pasting the link to individual Santa emails, Outlook breaks the link into two lines which the recipient will not see their target. I can use a TinyURL but was wondering if there is a feature to automatically do that.

Example: 
Unbroken link:
http://arcanis.github.io/secretsanta/pairing.html?name=Pat&key=52289&pairing=U2FsdGVkX1%2BaTaWTYv155oRr87otIB2nmhKbCJ2pTq8%3D

Outlook broken link:
http://arcanis.github.io/secretsanta/pairing.html?name=Pat&key=52289&pairing 
=U2FsdGVkX1%2BaTaWTYv155oRr87otIB2nmhKbCJ2pTq8%3D

Feature?
https://tinyurl.com/arcanisSantaPat

**Comment by arcanis** [comment]
Unfortunately no; since the service operates without a backend, we can't make the links shorter.
