### ISSUE TITLE
Link preview spoils names on iOS

### ISSUE THREAD

**Issue by PierreMesure** [arcanis/secretsanta#23]
Hi,

Great website!

I just tried to use it on an iPhone and I couldn't find a way to use it without getting spoiled because when I try and select the links, a preview opens and shows the name of the person that will receive the gifts.

A solution would be to add buttons to copy the link next to them:
Name / URL / "Copy" button

**Comment by leohmoraes** [comment]
In fact, it could be a problem with programs or apps that preview the url.

I have a personal system (old) where this first link only informs who is viewing and brings a second link/button that will then show the photo and name. This way, a lay person or a small child could just click the button, reveal their secret friend, and then close the window or the message will automatically disappear...

PS. Great ideia!

**Comment by Zeustopher** [comment]
I made a simple modification to wrap the paired name behind a "Reveal Name" button. This should be enough to fix the link preview issue as the name won't show until the button is clicked.

```html

<style>
    /* Existing styles */

    .reveal-button {
            background-color: #EF3D3D;
            color: white;
            border: none;
            margin-top: 5px;
            padding: 10px 20px;
            font-size: 16px;
            cursor: pointer;
            border-radius: 5px;
            box-shadow: 2px 2px 5px rgba(0, 0, 0, 0.3);
            transition: background-color 0.3s ease;
        }

        .reveal-button:hover {
            background-color: #FB3B3B;
        }
</style>

...

<div class="wrapper">
        <div class="content">

            <div class="title">Hi <span id="name"></span>!</div>
            <script>document.getElementById('name').innerText = name</script>
            <br>

            <div>You'll be giving to</div>
            <button id="reveal-button" class="reveal-button">Reveal Name</button>

            <div class="pairing">
                <div id="pairing-name"></div>
                <div id="pairing-details"></div>
            </div>

            <script>
                document.getElementById('reveal-button').addEventListener('click', function () {
                    document.getElementById('pairing-name').innerText = pairingDefinition[1];

                    if (pairingDefinition[2]) {
                        document.getElementById('pairing-details').innerText = pairingDefinition[2];
                    }
                    else {
                        document.getElementById('pairing-details').style.display = 'none';
                    }

                    document.querySelector('.pairing').style.display = 'block';
                    this.style.display = 'none';
                });
            </script>
            <br>

            <div class="title">Merry Christmas!</div>
        </div>
    </div>
```

Note especially the `<button id="reveal-button" class="reveal-button">Reveal Name</button>` and the corresponding ` document.getElementById('reveal-button').addEventListener('click', function () {` that will inject the name only after it is clicked.

**Comment by arcanis** [comment]
I deployed a new version which should solve the issue, as the links aren't links anymore (instead, clicking the button directly adds the link to your clipboard).
