### ISSUE TITLE
Multiple Name Elimination

### ISSUE THREAD

**Issue by Germaican03** [arcanis/secretsanta#4]
I love this by the way! Worked perfectly last year and it's so simple.

The issue I'm running into is having a name with more than 3 names as being unable to pair with. Ex: Joe can't pair with Schmo, Schmoo, Susie, etc...
Could I get an example of how it should be typed in the generator to ensure I'm doing it properly?

**Comment by arcanis** [comment]
Thanks! I believe it should be like this:

```
Joe !Schmo !Schmoo !Susie
Schmo
Schmoo
Susie
William
Norbert
Max
```

But I tried it and it doesn't seem to work well - I got Joe paired with Susie the first time I ran it 🤔 There's likely a bug, I can dig more into it later this month 🙂

**Comment by Germaican03** [comment]
Thanks a ton!

And I've shared this with friends by the way! I hate having to always register, give an email, or whatever other nonsense these other sites force you to do for such a simple calculation. Your program is so easy. Type the names, type who doesn't exchange with who, 'Submit', send links. No more having to ask 10 people for their emails.

**Comment by arcanis** [comment]
Bug fixed 🎉
