### ISSUE TITLE
Missing responsive design

### ISSUE THREAD

**Issue by AndreasInfo** [arcanis/secretsanta#7]
I would like to add some responsiveness, probably using Bootstrap.

As this would be my first contribution: Would it be apreciated?
Thanks, Andreas

**Comment by arcanis** [comment]
Hi Andreas! I'm planning to modernize it in a few weeks / months so I'd hold off on that, but thanks for the offer 😊

**Comment by daimhin** [comment]
Have you done any work on the modernizing?  I didn't see anything in this project but wasn't sure if it was opened into a new one.

**Comment by bmitchinson** [comment]
This app is awesome, just used it and am interested in making a clone without much santa in the design. Thanks for OSing it

**Comment by arcanis** [comment]
I released a new version which should be responsive 💫
