### ISSUE TITLE
Subscription Form

### ISSUE THREAD

**Issue by swishi** [arcanis/secretsanta#9]
Hi Maël
You realy did a great job with this script i will youse it this year for my secret santas! Due to COVID-19 i think it would be a great enhacment to ad a subscription form where the participiants can add themselves to participate and give their adress to where the gift should be sent. The Admin could distribute the link to that subscription Form and then at day x run the script tu have the participiants shuffeld... This would be the automatic version another one would be to store the subscriptions in a csv file wich could be inserted in the generate form os your script.

I Think following form fields would be enough
Name
Adress (Street, Nbr. Zip Code, City)
e-Mail Adress
Message to his secret Santa

Would be great to hear from you, salutations et a bientôt take care!
Ismael

**Comment by arcanis** [comment]
Hey,

Unfortunately this would require a database of some sort (to keep the information about the participants), and I'm afraid that's out of scope for this particular tool (it's meant to be a static page, and only a static page).

**Comment by swishi** [comment]
Thanks for your answer Maël... 

Well if the data of the subscription would be stored in a csv or txt file there would be no db used... the admin could copy the csv or txt in the field and run your script... 

Salutations Ismael
